services:
  db:
    image: postgres:16
    container_name: service_market_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 635221
      POSTGRES_DB: ServiceMarketplaceDb
    ports:
      - "5432:5432"
    volumes:
      - service_market_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: service_market_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL:  
      PGADMIN_DEFAULT_PASSWORD: 635221
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ServiceMarketAPI/Dockerfile
    container_name: service_market_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=ServiceMarketplaceDb;Username=postgres;Password=635221
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  service_market_db_data:
